In [1]:
import pandas as pd
import numpy as np

import xgboost as xgb
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.cross_validation import train_test_split
from sklearn import cross_validation

import operator
import matplotlib
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

In [2]:
# (1) read in data
print("Load the training, test and store data using pandas")
types = {'StateHoliday': np.dtype(str),
         'SchoolHoliday': np.dtype(float),
         'PromoInterval': np.dtype(str),
         'Assortment': np.dtype(str), 
         'PromoInterval': np.dtype(str),
         'StoreType': np.dtype(str)
        }


train_df = pd.read_csv("../data/train.csv", dtype=types)
store_df = pd.read_csv("../data/store.csv", dtype=types, keep_default_na=False, na_values= '')
test_df = pd.read_csv("../data/test.csv", dtype=types)

Load the training, test and store data using pandas

In [3]:
# (2) show data feature
#train_df[0:10]

In [4]:
#store_df[0:10]

In [5]:
print("\n"+"----train-------")
train_df.info()
print("\n"+"----store----------")
store_df.info()
print("\n"+"----test----------")
test_df.info()

----train-------
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
Store            1017209 non-null int64
DayOfWeek        1017209 non-null int64
Date             1017209 non-null object
Sales            1017209 non-null int64
Customers        1017209 non-null int64
Open             1017209 non-null int64
Promo            1017209 non-null int64
StateHoliday     1017209 non-null object
SchoolHoliday    1017209 non-null float64
dtypes: float64(1), int64(6), object(2)
memory usage: 77.6+ MB

----store----------
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1115 entries, 0 to 1114
Data columns (total 10 columns):
Store                        1115 non-null int64
StoreType                    1115 non-null object
Assortment                   1115 non-null object
CompetitionDistance          1112 non-null float64
CompetitionOpenSinceMonth    761 non-null float64
CompetitionOpenSinceYear     761 non-null float64
Promo2                       1115 non-null int64
Promo2SinceWeek              571 non-null float64
Promo2SinceYear              571 non-null float64
PromoInterval                571 non-null object
dtypes: float64(5), int64(2), object(3)
memory usage: 95.8+ KB

----test----------
<class 'pandas.core.frame.DataFrame'>
Int64Index: 41088 entries, 0 to 41087
Data columns (total 8 columns):
Id               41088 non-null int64
Store            41088 non-null int64
DayOfWeek        41088 non-null int64
Date             41088 non-null object
Open             41077 non-null float64
Promo            41088 non-null int64
StateHoliday     41088 non-null object
SchoolHoliday    41088 non-null float64
dtypes: float64(2), int64(4), object(2)
memory usage: 2.8+ MB

In [6]:
def describe_object(X):
    # return object variables only
    from IPython.display import display, HTML
    display(HTML(X[X.columns[X.dtypes == "object"]].describe().to_html()))
    
def show_object(X):
    category=np.unique(list(X.select_dtypes(['object'])))
    print("------------------Categorical Columns---------------------")
    print(category)
    print("\n")
    print("------------List all----------------------")
    for column in category:
        {
        print(column + ':' + str(np.unique(list(X[column])))+'\n')
        }

def show_object_No(X, No):
    category=np.unique(list(filter(lambda x: x!= No, X.select_dtypes(['object']))))
    print("----------Categorical Columns------remove-"+No+"--------------")
    print(category)
    print("\n")
    print("------------List all----------------------")
    for column in category:
        {
        print(column + ':' + str(np.unique(list(X[column])))+'\n')
        }
        
def show_object_NoList(X, NoList):
    category=np.unique(list(filter(lambda x: (x not in NoList), X.select_dtypes(['object']))))
    print("----------Categorical Columns---remove----"+', '.join(NoList)+"--------------")
    print(category)
    print("\n")
    print("------------List all----------------------")
    for column in category:
        {
        print(column + ':' + str(np.unique(list(X[column])))+'\n')
        }

In [7]:
describe_object(train_df)
show_object_No(train_df,'Date')
print("--------------------------")
describe_object(store_df)
show_object(store_df)

----------Categorical Columns------remove-Date--------------
['StateHoliday']


------------List all----------------------
StateHoliday:['0' 'a' 'b' 'c']

--------------------------

------------------Categorical Columns---------------------
['Assortment' 'PromoInterval' 'StoreType']


------------List all----------------------
Assortment:['a' 'b' 'c']

PromoInterval:['Feb,May,Aug,Nov' 'Jan,Apr,Jul,Oct' 'Mar,Jun,Sept,Dec' 'nan']

StoreType:['a' 'b' 'c' 'd']

In [8]:
# features_build: features List;  data (data frame in -> data frame out)
def features_build(features, data):
    # fill nan with 0
    data.fillna(0, inplace=True)
    #data.loc[data.open.isnull(), 'Open'] =1
    features.extend(['Store', 'CompetitionDistance', 'Promo', 'Promo2', 'SchoolHoliday'])
    
    # add columns (features list and then data import)
    #(1) categorical to 12345 mapping
    #features.extend['StoreType', 'Assortment', 'StateHoliday'] already have
    mappings = {'a':1, 'b':2, 'c':3, 'd':4, '0':0}
    data.StoreType.replace(mappings, inplace=True)
    data.Assortment.replace(mappings, inplace=True)
    data.StateHoliday.replace(mappings, inplace=True)
    
    #(2) Date 
    features.extend(['DayofWeek', 'Month', 'Day', 'Year', 'WeekofYear'])
    data['Year'] = pd.to_datetime(data.Date).dt.year
    data['Month'] = pd.to_datetime(data.Date).dt.month
    data['Day'] = pd.to_datetime(data.Date).dt.day
    data['DayofWeek'] = pd.to_datetime(data.Date).dt.dayofweek
    data['WeekofYear'] = pd.to_datetime(data.Date).dt.weekofyear
    
    #(3) Other time
    features.extend('CompetitionOpen_Month')
    data['CompetitionOpen_Month'] = (data.Month - data.CompetitionOpenSinceMonth) + 12 * (data.Year - data.CompetitionOpenSinceYear)
    
    features.extend('Promo2Since_Month')
    data['Promo2Since_Month'] = (data.WeekofYear - data.Promo2SinceWeek)/4 + 12 * (data.Year - data.Promo2SinceYear)
    data['Promo2Since_Month'] = data.Promo2Since_Month.apply(lambda x: x if x > 0 else 0)
    data.loc[data.Promo2SinceYear == 0, 'Promo2Since_Month'] = 0
    
    
    features.append('IsPromoMonth')
    month2str = {1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun', \
             7:'Jul', 8:'Aug', 9:'Sept', 10:'Oct', 11:'Nov', 12:'Dec'}
    data['monthStr'] = data.Month.map(month2str)
    data.loc[data.PromoInterval == 0, 'PromoInterval'] = ''
    data['IsPromoMonth'] = 0
    for interval in data.PromoInterval.unique():
        if interval != '':
            for month in interval.split(','):
                data.loc[(data.monthStr == month) & (data.PromoInterval == interval), 'IsPromoMonth'] = 1
                
    return data

In [9]:
##

In [10]:
print("Assume store open, if not provided")
test_df.fillna(1, inplace=True)

print("Consider only open stores for training. Closed stores wont count into the score.")
train_df = train_df[train_df["Open"] != 0]
print("Use only Sales bigger then zero")
train_df = train_df[train_df["Sales"] > 0]

print("Join with store")
train_df = pd.merge(train_df, store_df, on='Store')
test_df = pd.merge(test_df, store_df, on='Store')

Assume store open, if not provided
Consider only open stores for training. Closed stores wont count into the score.
Use only Sales bigger then zero
Join with store

In [11]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 844338 entries, 0 to 844337
Data columns (total 18 columns):
Store                        844338 non-null int64
DayOfWeek                    844338 non-null int64
Date                         844338 non-null object
Sales                        844338 non-null int64
Customers                    844338 non-null int64
Open                         844338 non-null int64
Promo                        844338 non-null int64
StateHoliday                 844338 non-null object
SchoolHoliday                844338 non-null float64
StoreType                    844338 non-null object
Assortment                   844338 non-null object
CompetitionDistance          842152 non-null float64
CompetitionOpenSinceMonth    575738 non-null float64
CompetitionOpenSinceYear     575738 non-null float64
Promo2                       844338 non-null int64
Promo2SinceWeek              421046 non-null float64
Promo2SinceYear              421046 non-null float64
PromoInterval                421046 non-null object
dtypes: float64(6), int64(7), object(5)
memory usage: 122.4+ MB

In [12]:
features = []

print("augment features")
train_df = features_build([features], train_df)
print(features)
test_df = features_build([], test_df)


print('training data processed')

def rmspe(y, yhat):
    return np.sqrt(np.mean(((y - yhat)/y) ** 2))

def rmspe_xg(yhat, y):
    y = np.expm1(y.get_label())
    yhat = np.expm1(yhat)
    return "rmspe", rmspe(y, yhat)

print("Train xgboost model")

params = {"objective": "reg:linear",
          "booster" : "gbtree",
          "eta": 0.1,
          "max_depth": 10,
          "subsample": 0.85,
          "colsample_bytree": 0.4,
          "min_child_weight": 6,
          "silent": 1,
          "thread": 1,
          "seed": 1301
          }
num_boost_round = 1200

augment features
[]
training data processed
Train xgboost model

In [13]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 844338 entries, 0 to 844337
Data columns (total 27 columns):
Store                        844338 non-null int64
DayOfWeek                    844338 non-null int64
Date                         844338 non-null object
Sales                        844338 non-null int64
Customers                    844338 non-null int64
Open                         844338 non-null int64
Promo                        844338 non-null int64
StateHoliday                 844338 non-null int64
SchoolHoliday                844338 non-null float64
StoreType                    844338 non-null int64
Assortment                   844338 non-null int64
CompetitionDistance          844338 non-null float64
CompetitionOpenSinceMonth    844338 non-null float64
CompetitionOpenSinceYear     844338 non-null float64
Promo2                       844338 non-null int64
Promo2SinceWeek              844338 non-null float64
Promo2SinceYear              844338 non-null float64
PromoInterval                844338 non-null object
Year                         844338 non-null int64
Month                        844338 non-null int64
Day                          844338 non-null int64
DayofWeek                    844338 non-null int64
WeekofYear                   844338 non-null int64
CompetitionOpen_Month        844338 non-null float64
Promo2Since_Month            844338 non-null float64
monthStr                     844338 non-null object
IsPromoMonth                 844338 non-null int64
dtypes: float64(8), int64(16), object(3)
memory usage: 180.4+ MB

In [14]:
train_df.describe()

,Store,DayOfWeek,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,...,Promo2SinceWeek,Promo2SinceYear,Year,Month,Day,DayofWeek,WeekofYear,CompetitionOpen_Month,Promo2Since_Month,IsPromoMonth
count,844338.000000,844338.000000,844338.000000,844338.000000,844338,844338.000000,844338.000000,844338.000000,844338.000000,844338.000000,...,844338.000000,844338.000000,844338.000000,844338.000000,844338.000000,844338.000000,844338.000000,844338.000000,844338.000000,844338.000000
mean,558.421374,3.520350,6955.959134,762.777166,1,0.446356,0.001418,0.193578,2.205441,1.936493,...,11.596159,1003.201259,2013.831945,5.845774,15.835706,2.520350,23.646946,7730.589779,13.053234,0.171984
std,321.730861,1.723712,3103.815515,401.194153,0,0.497114,0.047578,0.395102,1.363375,0.993099,...,15.308101,1005.874685,0.777271,3.323959,8.683392,1.723712,14.389931,11230.049970,18.973591,0.377367
min,1.000000,1.000000,46.000000,8.000000,1,0.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,2013.000000,1.000000,1.000000,0.000000,1.000000,-31.000000,0.000000,0.000000
25%,280.000000,2.000000,4859.000000,519.000000,1,0.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,2013.000000,3.000000,8.000000,1.000000,11.000000,29.000000,0.000000,0.000000
50%,558.000000,3.000000,6369.000000,676.000000,1,0.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,2014.000000,6.000000,16.000000,2.000000,23.000000,91.000000,0.000000,0.000000
75%,837.000000,5.000000,8360.000000,893.000000,1,1.000000,0.000000,0.000000,4.000000,3.000000,...,22.000000,2012.000000,2014.000000,8.000000,23.000000,4.000000,35.000000,24163.000000,25.000000,0.000000
max,1115.000000,7.000000,41551.000000,7388.000000,1,1.000000,3.000000,1.000000,4.000000,3.000000,...,50.000000,2015.000000,2015.000000,12.000000,31.000000,6.000000,52.000000,24187.000000,72.000000,1.000000